spring:
  main:
    banner-mode: off
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  task:
    execution:
      pool:
        core-size: 6
        max-size: 36
        keep-alive: 60s
        queue-capacity: 128
      thread-name-prefix: worker-
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 123456
    url: jdbc:postgresql://localhost:5432/media
  codec:
    max-in-memory-size: 100MB
  mail:
    host: smtp.163.com
#    port: 465
    username: 18906733062@163.com
    password: "FCMWNKRZFHELUGCK"
    default-encoding: UTF-8
    protocol: smtp
    properties:
      mail:
        pop3:
          auth: true
          starttls:
            enable: true
        smtp:
          auth: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
          starttls:
            enable: true
log4jdbc:
  drivers: org.postgresql.Driver
  auto:
    load:
      popular:
        drivers: false
  dump:
    sql:
      maxlinelength: 0

application:
  base-url: "http://127.0.0.1"
  auth:
    password-regex: '^(?![a-zA-Z]+$)(?!\d+$)(?![^\da-zA-Z\s]+$).{6,16}$'
    max-session: 3
    # 有效期时长
    duration: 30d
    # 忘记密码
    forget:
      # 请求有效期
      duration: 7d
      base-url: "${application.base-url}/auth/resetPassword"
  media:
    tag:
      rule: "^[^,\\|/$!\\s]+$"
    mongodb:
      uri: mongodb://admin:123456@localhost:27017/media?authSource=admin
      database: media
      media: media
  files:
    dir: data

logging:
  config: classpath:logback-spring.xml

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
  global-config:
    banner: false
server:
  compression:
    enabled: true
    min-response-size: 2KB
    mime-types: "*/*"
  port: 8000
